format = """[│](bold cyan)$directory$git_branch$git_status
[└─❯](bold cyan) """

right_format = "[$time$cmd_duration$status$kubernetes](bold cyan)"

[kubernetes]
disabled = false
format = ' [$symbol$context( \($namespace\))](bold cyan)'

[time]
format = "[$time](bold cyan)"
disabled = false

[status]
format = " [$symbol$status](bold cyan)"
disabled = false

[git_branch]
format = "[on](cyan) [$branch](bold cyan)"

[git_status]
format = '([\[$all_status$ahead_behind\]](cyan))'
conflicted = '!\($count\)'
ahead = '⇡\($count\)'
behind = '⇣\($count\)'
diverged = '⇡\($ahead_count\)⇣\($behind_count\)'
untracked = '?\($count\)'
modified = '+\($count\)'
staged = '✓\($count\)'
renamed = '»\($count\)'
deleted = '✘\($count\)'

[directory]
format = "[$path/](bold cyan)[$read_only]($read_only_style) "

[cmd_duration]
format = " $duration"

